Repository mentortechabc/play, pull requests merged in 2021-07, with the labels that each got.

#41 Create all tables
  .gitignore
  calendar-admin/db.py
  calendar-admin/tests/test_db.py
Labels: enhancement

#60 TODO for socket_server
  leop/http/htdocs/index.html
  leop/http/htdocs/ipsum.html
  leop/http/socket_server.py
Labels: enhancement

#73 fix bugs and opimise and add delete_all
  calendar-admin/add_interval.py
  calendar-admin/comand_line_parser.py
  calendar-admin/convert_time.py
  calendar-admin/delete_all.py
  calendar-admin/delete_day.py
  calendar-admin/delete_interval.py
  calendar-admin/get_slots.py
  calendar-admin/tests/func_for_test_db.py
Labels: bug

#76 fix bug single booking interval
  calendar-admin/convert_time.py
Labels: bug

#64 Renamed start_date into start_interval
  calendar-admin/db.py
  calendar-admin/tests/test_db.py
Labels: bug

#84 add sort to get_slots and optimise test_get_slots
  calendar-admin/convert_time.py
  calendar-admin/get_slots.py
  calendar-admin/tests/test_get_slots.py
Labels: priority:low

#83 Topic is now optional in BookingInfo Table (db&test are fixed)
  calendar-admin/db.py
  calendar-admin/tests/test_db.py
Labels: bug

#85 feat(Flask App): add Flask app with DB
  leop/.gitignore
  leop/flask/README.md
  leop/flask/appointments.py
  leop/flask/create.sql
  leop/flask/db.py
  leop/flask/templates/appointments.html
  leop/requirements.txt
Labels: enhancement
